import SchurCohn

#check @Polynomial.reflect
#check @Polynomial.coeff_reflect
#check @Polynomial.reflect_reflect
#check @Polynomial.reflect_map
#check @Polynomial.reflect_mul
#check @Polynomial.natDegree_reflect_le
#check @Polynomial.eval₂_reflect_mul_pow
#check @Polynomial.reflect_add
#check @Polynomial.reflect_sub
#check @Polynomial.reflect_C_mul
#check @Polynomial.reflect_C
#check @Polynomial.revAt
#check @Polynomial.divX
#check @Polynomial.coeff_divX
#check @Polynomial.X_mul_divX_add
#check @Polynomial.natDegree_divX_eq_natDegree_tsub_one
#check @IsAlgClosed.splits
#check @Polynomial.Splits.eq_prod_roots
#check @Polynomial.Splits.eval_eq_prod_roots
#check @IsAlgClosed.card_roots_eq_natDegree
#check @Polynomial.Splits.coeff_zero_eq_leadingCoeff_mul_prod_roots
#check @Polynomial.C_leadingCoeff_mul_prod_multiset_X_sub_C
#check @Complex.mul_conj
#check @Complex.normSq_eq_norm_sq
#check @Complex.norm_conj
#check @Complex.norm_mul
#check @Multiset.prod_map_le_prod_map₀
#check @Polynomial.eval_multiset_prod
#check @Polynomial.coeff_map
#check @Polynomial.eval_map
#check @SchurCohn.conjRecip
#check @SchurCohn.IsStable
#check @SchurCohn.coeff_conjRecip
#check @SchurCohn.coeff_conjRecip_of_le
#check @SchurCohn.coeff_conjRecip_of_lt
#check @SchurCohn.conjRecip_coeff_zero
#check @SchurCohn.conjRecip_coeff_self
#check @SchurCohn.conjRecip_conjRecip
#check @SchurCohn.natDegree_conjRecip_le
#check @SchurCohn.conjRecip_add
#check @SchurCohn.conjRecip_sub
#check @SchurCohn.conjRecip_C_mul
#check @SchurCohn.conjRecip_zero
#check @SchurCohn.conjRecip_C
#check @SchurCohn.conjRecip_X_mul
#check @SchurCohn.conjRecip_mul
#check @SchurCohn.eval_conjRecip
#check @SchurCohn.norm_eval_conjRecip_of_norm_eq_one
#check @SchurCohn.conjRecip_ne_reverse
#check @SchurCohn.not_isStable_zero
#check @SchurCohn.isStable_C
#check @SchurCohn.isStable_iff_of_natDegree_eq_zero
#check @SchurCohn.isStable_C_mul_iff
#check @SchurCohn.isStable_iff_roots
#check @SchurCohn.lemmaA
#check @SchurCohn.lemmaA_normSq
#check @SchurCohn.norm_one_sub_conj_mul_le
#check @SchurCohn.norm_one_sub_conj_mul_lt
#check @SchurCohn.norm_one_sub_conj_mul_eq
#check @SchurCohn.eval_eq_prod_roots_of_natDegree
#check @SchurCohn.conjRecip_eq_prod_roots
#check @SchurCohn.lemmaB
#check @SchurCohn.lemmaB_strict
#check @SchurCohn.lemmaB_eq_iff
#check @SchurCohn.lemmaC
#check @SchurCohn.schur
#check @SchurCohn.coeff_zero_schurNumerator
#check @SchurCohn.X_mul_schur
#check @SchurCohn.coeff_schur
#check @SchurCohn.natDegree_schur_le
#check @SchurCohn.coeff_schur_pred
#check @SchurCohn.natDegree_schur_eq
#check @SchurCohn.schur_ne_zero
#check @SchurCohn.conjRecip_schur
#check @SchurCohn.schur_identity
#check @SchurCohn.isStable_schur_of_isStable
#check @SchurCohn.isStable_of_isStable_schur
#check @SchurCohn.isStable_iff_schur
#check @SchurCohn.SchurTest
#check @SchurCohn.schurTest_iff
#check @SchurCohn.schurTest_iff_of_natDegree_eq
#check @SchurCohn.GZ
#check @SchurCohn.GQ
#check @SchurCohn.GZ.toC
#check @SchurCohn.GQ.toC
#check @SchurCohn.GZ.normSq
#check @SchurCohn.GQ.normSq
#check @SchurCohn.GZ.toC_add
#check @SchurCohn.GZ.toC_sub
#check @SchurCohn.GZ.toC_mul
#check @SchurCohn.GZ.toC_conj
#check @SchurCohn.GZ.normSq_toC
#check @SchurCohn.GZ.toC_eq_zero
#check @SchurCohn.GQ.toC_mul
#check @SchurCohn.GQ.normSq_toC
#check @SchurCohn.toPoly
#check @SchurCohn.toPolyQ
#check @SchurCohn.coeff_toPoly
#check @SchurCohn.natDegree_toPoly_le
#check @SchurCohn.schurList
#check @SchurCohn.length_schurList
#check @SchurCohn.toPoly_schurList
#check @SchurCohn.checkAux
#check @SchurCohn.check
#check @SchurCohn.checkAux_iff
#check @SchurCohn.check_iff
#check @SchurCohn.denProd
#check @SchurCohn.toGZ
#check @SchurCohn.checkQ
#check @SchurCohn.toPoly_toGZ
#check @SchurCohn.checkQ_iff
#check @SchurCohn.pilot_check
#check @SchurCohn.pilot_isStable
#check @SchurCohn.ar2_triangle
#check @SchurCohn.real_quadratic_iff
#check @SchurCohn.jury_cubic
#check @SchurCohn.arPoly
#check @SchurCohn.IsStationaryK
#check @SchurCohn.phiDownK
#check @SchurCohn.isStationaryK_iff_isStable
#check @SchurCohn.schur_arPoly
#check @SchurCohn.isStable_arPoly_iff_stepDown
#check @SchurCohn.isStationaryK_iff_stepDown
#check @SchurCohn.spectralPeak_imp_complexRoots
