import SchurCohn

/-!
# Statement conformance (C4.D and C4.LEM)

Every C4.D and C4.LEM statement of the C4.B statement file
(`deliverables/C4.B/statements/SchurCohnStatements.lean` at `20d4440`, section
"Definitions and conjugate-reciprocal API (C4.D)" and "Lemmas A–C (C4.LEM)"), copied verbatim
and closed by the corresponding `SchurCohn` declaration. The file is generated by
`checks/gen_conformance.py`; it compiles only if every proved statement is the blueprint
statement. The three definitions are checked against the blueprint bodies by `rfl`.
-/

open Polynomial ComplexConjugate SchurCohn

/-! ## Definitions: the blueprint bodies -/

example (n : ℕ) (p : ℂ[X]) : conjRecip n p = (p.map (starRingEnd ℂ)).reflect n := rfl

example (p : ℂ[X]) : IsStable p = (p ≠ 0 ∧ ∀ z : ℂ, p.IsRoot z → ‖z‖ < 1) := rfl

example (n : ℕ) (p : ℂ[X]) :
    schur n p = (C (conj (p.coeff n)) * p - C (p.coeff 0) * conjRecip n p).divX := rfl

/-! ## Lemma A (`lem:A`), as in the statement file -/

example (α z : ℂ) :
    ‖z - α‖ ^ 2 - ‖1 - conj α * z‖ ^ 2 = (‖z‖ ^ 2 - 1) * (1 - ‖α‖ ^ 2) :=
  SchurCohn.lemmaA α z

/-! ## Theorems -/
