import SchurCohn

/-!
# Statement conformance (C4.D and C4.LEM)

Every C4.D and C4.LEM statement of the C4.B statement file
(`deliverables/C4.B/statements/SchurCohnStatements.lean` at `20d4440`, section
"Definitions and conjugate-reciprocal API (C4.D)" and "Lemmas A–C (C4.LEM)"), copied verbatim
and closed by the corresponding `SchurCohn` declaration. The file is generated by
`checks/gen_conformance.py`; it compiles only if every proved statement is the blueprint
statement. The three definitions are checked against the blueprint bodies by `rfl`.
-/

open Polynomial ComplexConjugate SchurCohn

/-! ## Definitions: the blueprint bodies -/

example (n : ℕ) (p : ℂ[X]) : conjRecip n p = (p.map (starRingEnd ℂ)).reflect n := rfl

example (p : ℂ[X]) : IsStable p = (p ≠ 0 ∧ ∀ z : ℂ, p.IsRoot z → ‖z‖ < 1) := rfl

example (n : ℕ) (p : ℂ[X]) :
    schur n p = (C (conj (p.coeff n)) * p - C (p.coeff 0) * conjRecip n p).divX := rfl

/-! ## Lemma A (`lem:A`), as in the statement file -/

example (α z : ℂ) :
    ‖z - α‖ ^ 2 - ‖1 - conj α * z‖ ^ 2 = (‖z‖ ^ 2 - 1) * (1 - ‖α‖ ^ 2) :=
  SchurCohn.lemmaA α z

/-! ## Theorems -/

-- `coeff_conjRecip`
example (n k : ℕ) (p : ℂ[X]) :
    (conjRecip n p).coeff k = conj (p.coeff (revAt n k)) :=
  SchurCohn.coeff_conjRecip (n := n) (k := k) (p := p)

-- `coeff_conjRecip_of_le`
example {n k : ℕ} (p : ℂ[X]) (hk : k ≤ n) :
    (conjRecip n p).coeff k = conj (p.coeff (n - k)) :=
  SchurCohn.coeff_conjRecip_of_le (n := n) (k := k) (p := p) (hk := hk)

-- `coeff_conjRecip_of_lt`
example {n k : ℕ} {p : ℂ[X]} (hp : p.natDegree ≤ n) (hk : n < k) :
    (conjRecip n p).coeff k = 0 :=
  SchurCohn.coeff_conjRecip_of_lt (n := n) (k := k) (p := p) (hp := hp) (hk := hk)

-- `conjRecip_coeff_zero`
example (n : ℕ) (p : ℂ[X]) :
    (conjRecip n p).coeff 0 = conj (p.coeff n) :=
  SchurCohn.conjRecip_coeff_zero (n := n) (p := p)

-- `conjRecip_coeff_self`
example (n : ℕ) (p : ℂ[X]) :
    (conjRecip n p).coeff n = conj (p.coeff 0) :=
  SchurCohn.conjRecip_coeff_self (n := n) (p := p)

-- `conjRecip_conjRecip`
example (n : ℕ) (p : ℂ[X]) :
    conjRecip n (conjRecip n p) = p :=
  SchurCohn.conjRecip_conjRecip (n := n) (p := p)

-- `natDegree_conjRecip_le`
example {n : ℕ} {p : ℂ[X]} (hp : p.natDegree ≤ n) :
    (conjRecip n p).natDegree ≤ n :=
  SchurCohn.natDegree_conjRecip_le (n := n) (p := p) (hp := hp)

-- `conjRecip_add`
example (n : ℕ) (p r : ℂ[X]) :
    conjRecip n (p + r) = conjRecip n p + conjRecip n r :=
  SchurCohn.conjRecip_add (n := n) (p := p) (r := r)

-- `conjRecip_sub`
example (n : ℕ) (p r : ℂ[X]) :
    conjRecip n (p - r) = conjRecip n p - conjRecip n r :=
  SchurCohn.conjRecip_sub (n := n) (p := p) (r := r)

-- `conjRecip_C_mul`
example (n : ℕ) (c : ℂ) (p : ℂ[X]) :
    conjRecip n (C c * p) = C (conj c) * conjRecip n p :=
  SchurCohn.conjRecip_C_mul (n := n) (c := c) (p := p)

-- `conjRecip_zero`
example (n : ℕ) : conjRecip n 0 = 0 :=
  SchurCohn.conjRecip_zero (n := n)

-- `conjRecip_C`
example (c : ℂ) : conjRecip 0 (C c) = C (conj c) :=
  SchurCohn.conjRecip_C (c := c)

-- `conjRecip_X_mul`
example {n : ℕ} (hn : 1 ≤ n) {q : ℂ[X]} (hq : q.natDegree ≤ n - 1) :
    conjRecip n (X * q) = conjRecip (n - 1) q :=
  SchurCohn.conjRecip_X_mul (n := n) (hn := hn) (q := q) (hq := hq)

-- `conjRecip_mul`
example {F G : ℕ} {f g : ℂ[X]} (hf : f.natDegree ≤ F) (hg : g.natDegree ≤ G) :
    conjRecip (F + G) (f * g) = conjRecip F f * conjRecip G g :=
  SchurCohn.conjRecip_mul (F := F) (G := G) (f := f) (g := g) (hf := hf) (hg := hg)

-- `eval_conjRecip`
example {n : ℕ} {p : ℂ[X]} (hp : p.natDegree ≤ n) {z : ℂ} (hz : z ≠ 0) :
    (conjRecip n p).eval z = z ^ n * conj (p.eval (conj z)⁻¹) :=
  SchurCohn.eval_conjRecip (n := n) (p := p) (hp := hp) (z := z) (hz := hz)

-- `norm_eval_conjRecip_of_norm_eq_one`
example {n : ℕ} {p : ℂ[X]} (hp : p.natDegree ≤ n) {z : ℂ}
    (hz : ‖z‖ = 1) : ‖(conjRecip n p).eval z‖ = ‖p.eval z‖ :=
  SchurCohn.norm_eval_conjRecip_of_norm_eq_one (n := n) (p := p) (hp := hp) (z := z) (hz := hz)

-- `conjRecip_ne_reverse`
example :
    conjRecip 2 (X : ℂ[X]) = X ∧ ((X : ℂ[X]).map (starRingEnd ℂ)).reverse = 1 ∧
      ((X ^ 2 - X : ℂ[X]).reverse).reverse = X - 1 :=
  SchurCohn.conjRecip_ne_reverse

-- `not_isStable_zero`
example : ¬ IsStable 0 :=
  SchurCohn.not_isStable_zero

-- `isStable_C`
example {c : ℂ} (hc : c ≠ 0) : IsStable (C c) :=
  SchurCohn.isStable_C (c := c) (hc := hc)

-- `isStable_iff_of_natDegree_eq_zero`
example {p : ℂ[X]} (hp : p.natDegree = 0) :
    IsStable p ↔ p.coeff 0 ≠ 0 :=
  SchurCohn.isStable_iff_of_natDegree_eq_zero (p := p) (hp := hp)

-- `isStable_C_mul_iff`
example {c : ℂ} (hc : c ≠ 0) {p : ℂ[X]} :
    IsStable (C c * p) ↔ IsStable p :=
  SchurCohn.isStable_C_mul_iff (c := c) (hc := hc) (p := p)

-- `isStable_iff_roots`
example {p : ℂ[X]} :
    IsStable p ↔ p ≠ 0 ∧ ∀ w ∈ p.roots, ‖w‖ < 1 :=
  SchurCohn.isStable_iff_roots (p := p)

-- `norm_one_sub_conj_mul_le`
example {α z : ℂ} (hα : ‖α‖ < 1) (hz : 1 ≤ ‖z‖) :
    0 < ‖z - α‖ ∧ ‖1 - conj α * z‖ ≤ ‖z - α‖ :=
  SchurCohn.norm_one_sub_conj_mul_le (α := α) (z := z) (hα := hα) (hz := hz)

-- `norm_one_sub_conj_mul_lt`
example {α z : ℂ} (hα : ‖α‖ < 1) (hz : 1 < ‖z‖) :
    ‖1 - conj α * z‖ < ‖z - α‖ :=
  SchurCohn.norm_one_sub_conj_mul_lt (α := α) (z := z) (hα := hα) (hz := hz)

-- `norm_one_sub_conj_mul_eq`
example (α : ℂ) {z : ℂ} (hz : ‖z‖ = 1) :
    ‖1 - conj α * z‖ = ‖z - α‖ :=
  SchurCohn.norm_one_sub_conj_mul_eq (α := α) (z := z) (hz := hz)

-- `eval_eq_prod_roots_of_natDegree`
example {p : ℂ[X]} {n : ℕ} (hp : p.natDegree = n) (z : ℂ) :
    Multiset.card p.roots = n ∧ p.coeff n = p.leadingCoeff ∧
      p.eval z = p.coeff n * (p.roots.map (fun w => z - w)).prod :=
  SchurCohn.eval_eq_prod_roots_of_natDegree (p := p) (n := n) (hp := hp) (z := z)

-- `conjRecip_eq_prod_roots`
example {p : ℂ[X]} {n : ℕ} (hp : p.natDegree = n) :
    conjRecip n p =
      C (conj (p.coeff n)) * (p.roots.map (fun w => 1 - C (conj w) * X)).prod :=
  SchurCohn.conjRecip_eq_prod_roots (p := p) (n := n) (hp := hp)

-- `lemmaB`
example {p : ℂ[X]} {n : ℕ} (hs : IsStable p) (hp : p.natDegree = n) {z : ℂ}
    (hz : 1 ≤ ‖z‖) : p.eval z ≠ 0 ∧ ‖(conjRecip n p).eval z‖ ≤ ‖p.eval z‖ :=
  SchurCohn.lemmaB (p := p) (n := n) (hs := hs) (hp := hp) (z := z) (hz := hz)

-- `lemmaB_strict`
example {p : ℂ[X]} {n : ℕ} (hs : IsStable p) (hp : p.natDegree = n) (hn : 1 ≤ n)
    {z : ℂ} (hz : 1 < ‖z‖) : ‖(conjRecip n p).eval z‖ < ‖p.eval z‖ :=
  SchurCohn.lemmaB_strict (p := p) (n := n) (hs := hs) (hp := hp) (hn := hn) (z := z) (hz := hz)

-- `lemmaB_eq_iff`
example {p : ℂ[X]} {n : ℕ} (hs : IsStable p) (hp : p.natDegree = n) (hn : 1 ≤ n)
    {z : ℂ} (hz : 1 ≤ ‖z‖) : ‖(conjRecip n p).eval z‖ = ‖p.eval z‖ ↔ ‖z‖ = 1 :=
  SchurCohn.lemmaB_eq_iff (p := p) (n := n) (hs := hs) (hp := hp) (hn := hn) (z := z) (hz := hz)

-- `lemmaC`
example {p : ℂ[X]} {n : ℕ} (hs : IsStable p) (hp : p.natDegree = n) (hn : 1 ≤ n) :
    ‖p.coeff 0‖ < ‖p.coeff n‖ :=
  SchurCohn.lemmaC (p := p) (n := n) (hs := hs) (hp := hp) (hn := hn)
